### ISSUE TITLE
Can't verify username

### ISSUE THREAD

**Issue by planetofadventures** [npersonn/integrate-polarsteps#4]
HI, many thanks for developing this plugin, unfortunately I'm unable to verify my username. I have tried several times over several days with no luck. Anything you could suggest?
My site is planetofadventures.com and the username is planetofadventures
https://www.polarsteps.com/planetofadventures
Many thanks in advance!

**Comment by npersonn** [comment]
Hi, 
there has been an issue with SSL3 on the connection. I updated the plugin accordingly in #5 .
Please note that PHP7 and curl-extension is now needed. Enjoy your travels!
